### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/actividad-4-mapa-mental-calidad-de-software-Rosa218#1]
[(Inglés).pdf](https://github.com/user-attachments/files/17103170/Ingles.pdf)

**Comment by Nelsy21** [comment]
Redacción y ortografía: 3.33333
Exposición de ideas centrales: 3.3333
Organización de la información: 3.3333
Uso de imagines y colores: 3.3333
Presentación visual: 3.3333
Creatividad: 3.3333

porcentaje final:100%
Calificación final: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
